# CircleCI Configuration - AWS ECS Deployment
# Copy this file to .circleci/config.yml to use it
# Deploys your containerized app to AWS ECS (Elastic Container Service)
# Required Environment Variables (set in CircleCI Project Settings):
#   - AWS_ACCESS_KEY_ID: Your AWS access key
#   - AWS_SECRET_ACCESS_KEY: Your AWS secret key
#   - AWS_REGION: AWS region (e.g., us-east-1)
#   - AWS_ECR_REGISTRY: Your ECR registry URL (e.g., 123456789.dkr.ecr.us-east-1.amazonaws.com)
#   - AWS_ECS_CLUSTER: ECS cluster name
#   - AWS_ECS_SERVICE: ECS service name

version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.0
  aws-ecs: circleci/aws-ecs@4.0.0

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest test_app.py -v
            echo "✓ Tests passed"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - aws-ecr/build_and_push_image:
          requires:
            - test
          filters:
            branches:
              only: main
          repo: hackathon-app
          tag: ${CIRCLE_SHA1},latest
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          family: hackathon-app
          cluster: ${AWS_ECS_CLUSTER}
          service-name: ${AWS_ECS_SERVICE}
          container-image-name-updates: container=hackathon-app,tag=${CIRCLE_SHA1}

