# CircleCI Configuration - AWS Lambda Deployment
# Copy this file to .circleci/config.yml to use it
# Required Environment Variables (set in CircleCI Project Settings):
#   - AWS_ACCESS_KEY_ID: Your AWS access key
#   - AWS_SECRET_ACCESS_KEY: Your AWS secret key
#   - AWS_LAMBDA_FUNCTION_NAME: Name of your Lambda function
#   - AWS_REGION: AWS region (e.g., us-east-1)

version: 2.1

orbs:
  python: circleci/python@2.1.0
  aws-cli: circleci/aws-cli@4.1.0

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest test_app.py -v
            echo "✓ Tests passed"

  deploy-to-aws:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install dependencies into package directory
          command: |
            mkdir -p package
            pip install -r requirements.txt -t package/
            cp app.py package/
      - run:
          name: Create deployment package
          command: |
            cd package
            zip -r ../deployment.zip .
            cd ..
            echo "✓ Deployment package created"
      - run:
          name: Deploy to AWS Lambda
          command: |
            aws lambda update-function-code \
              --function-name $AWS_LAMBDA_FUNCTION_NAME \
              --zip-file fileb://deployment.zip \
              --region $AWS_REGION
            echo "✓ Deployed to AWS Lambda: $AWS_LAMBDA_FUNCTION_NAME"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - deploy-to-aws:
          requires:
            - test
          filters:
            branches:
              only: main

