# CircleCI Configuration - Azure Functions Deployment
# Copy this file to .circleci/config.yml to use it
# Required Environment Variables (set in CircleCI Project Settings):
#   - AZURE_FUNCTION_APP_NAME: Name of your Azure Function App
#   - AZURE_RESOURCE_GROUP: Azure resource group name
#   - AZURE_SP_APP_ID: Service principal app ID
#   - AZURE_SP_PASSWORD: Service principal password
#   - AZURE_SP_TENANT: Azure tenant ID

version: 2.1

orbs:
  python: circleci/python@2.1.0
  azure-cli: circleci/azure-cli@2.0.0

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest test_app.py -v
            echo "✓ Tests passed"

  deploy-to-azure:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - azure-cli/install
      - run:
          name: Login to Azure
          command: |
            az login --service-principal \
              -u $AZURE_SP_APP_ID \
              -p $AZURE_SP_PASSWORD \
              --tenant $AZURE_SP_TENANT
            echo "✓ Authenticated with Azure"
      - run:
          name: Create deployment package
          command: |
            mkdir -p package
            pip install -r requirements.txt -t package/
            cp app.py package/
            cd package
            zip -r ../deployment.zip .
            cd ..
            echo "✓ Deployment package created"
      - run:
          name: Deploy to Azure Functions
          command: |
            az functionapp deployment source config-zip \
              -g $AZURE_RESOURCE_GROUP \
              -n $AZURE_FUNCTION_APP_NAME \
              --src deployment.zip
            echo "✓ Deployed to Azure Functions: $AZURE_FUNCTION_APP_NAME"
      - run:
          name: Get Function URL
          command: |
            az functionapp show \
              -g $AZURE_RESOURCE_GROUP \
              -n $AZURE_FUNCTION_APP_NAME \
              --query defaultHostName -o tsv

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - deploy-to-azure:
          requires:
            - test
          filters:
            branches:
              only: main

